/**
 * Lista completa de grupos deportivos de la Universidad del Valle
 */

export const GRUPOS_DEPORTIVOS = [
  "Ajedrez Representativo",
  "Ajedrez Funcionarios",
  "Ajedrez Semillero",
  "Atletismo Representativo Estudiantes y Funcionarios",
  "Atletismo Semillero",
  "Baloncesto Representativo",
  "Baloncesto Funcionarios",
  "Balonmano Representativo Femenino y Masculino",
  "Bolos Funcionarios Femenino y Masculino",
  "Fútbol Femenino Representativo",
  "Fútbol Masculino Representativo",
  "Fútbol Masculino Semillero",
  "Fútbol Master",
  "Fútbol Libre",
  "Fútbol Sala Femenino Representativo y Semillero",
  "Fútbol Sala Masculino Representativo",
  "Fútbol Sala Masculino Funcionarios",
  "Judo",
  "Karate do",
  "Muay Thai y Sanda",
  "Natación Representativo Femenino y Masculino",
  "Natación Semillero Femenino y Masculino",
  "Natación Funcionarios",
  "Natación con Aletas",
  "Patinaje Representativo",
  "Patinaje Semillero",
  "Polo Acuático Femenino",
  "Polo Acuático Masculino",
  "Porrismo Representativo",
  "Porrismo Semillero",
  "Rugby Femenino Representativo y Semillero",
  "Rugby Masculino Representativo",
  "Rugby Masculino Semillero",
  "Rugby Masculino - Preparacion fisica",
  "Sapo Funcionarios Femenino y Masculino Sintraunicol",
  "Taekwondo Representativo Femenino, Masculino y Semillero",
  "Tejo Funcionarios Sintraunicol",
  "Mini Tejo Funcionarios Sintraunicol",
  "Mini Tejo Funcionarios Sintraempuvalle",
  "Tenis de Campo Representativo Femenino y Masculino - Semillero Femenino y Masculino",
  "Tenis de Campo Funcionarios",
  "Tenis de Mesa Representativo Femenino y Masculino",
  "Tenis de Mesa Funcionarios",
  "Ultimate Representativo Femenino y Masculino",
  "Ultimate Semillero",
  "Voleibol Funcionarias Sintraunicol Femenino",
  "Voleibol Funcionarias Femenino",
  "Voleibol Funcionarios Masculino",
  "Voleibol Representativo Femenino y Masculino",
  "Voleibol Semillero",
  "Voleibol Arena Representativo",
  "Voleibol Arena Semillero",
  "Voleibol Arena Funcionarios",
] as const

export type GrupoDeportivo = typeof GRUPOS_DEPORTIVOS[number]
